language: rust

os: linux

dist: bionic

arch:
  - amd64

rust:
  - stable
  - 1.39.0
  - beta
  - nightly

jobs:
  include:
    - arch: arm64
    - arch: s390x
    - arch: ppc64le
    - os: osx
    - arch: amd64
      env: CARGO_BUILD_TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          packages:
            << *apt_default
            - libc6-i386
            - lib32gcc1
            - gcc-multilib

  allow_failures:
    - rust: nightly

addons:
  apt:
    packages: &apt_default
      - binutils-dev
      - libiberty-dev

# Using the homebrew addon suffers from a bug:
# https://travis-ci.community/t/macos-build-fails-because-of-homebrew-bundle-unknown-command/7296/27
before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then brew install binutils; fi

install:
  - ./scripts/rustup-extras.sh

script:
  - cargo test --verbose

notifications:
  email: false
