[package]
name = "lightning-sys"
version = "0.2.1"
authors = ["Peter Elliott <pelliott@ualberta.ca>"]
edition = "2018"
license = "LGPL-3.0-or-later"
description = "GNU lightning bindings for rust"
readme = "README.md"
repository = "https://github.com/petelliott/lightning-sys"
documentation = "https://docs.rs/lightning-sys"

[dependencies]
paste = "0.1.18"
lazy_static = "1.4.0"
tt-call = "1.0"

[build-dependencies]
attohttpc = { version = "0.15", default-features = false }
bindgen = "0.54.1"
cc = "1.0"
flate2 = "1.0"
tar = "0.4"

[dev-dependencies]
libc = "0.2"

[features]
default = ["disassembly"]
disassembly = []
